import cardImg from '../../user/home/posts/assets/images/post1.png';

export const postData = [
  {
    id: 1,
    img: cardImg,
    name: `106-maktab ma'muriyati`,
    date: '09:30, 23-sentabr',
    comment: 12,
    title: `🚦YO'L QOIDASI-UMR FOYDASI`,
    descr: `Olmazor tumanida joylashgan 106-sonli ixtisoslashtirilgan maktab internatida, "Gross" sug’urta kompaniyasi hamda Toshkent shahar IIBB hamkorligida, “Yo’l harakati intizomi bolalikdan boshlanadi”, “Yo’llarda bolalarni asraylik” shiorlari ostida bayramona targ’ibot tadbiri bo’lib o’tdi. Tadbir so’ngida bolajonlarga estalik sovg’alar topshirildi!`,
    link: '#',
  },
  {
    id: 2,
    img: cardImg,
    name: `242-maktab ma'muriyati`,
    date: '09:30, 20-oktabr',
    comment: 17,
    title: `Energiya tejamkorligi`,
    descr: `Olmazor tumanidagi 242-maktab jamoasi “Energiya tejamkorligi bo‘yicha eng yaxshi maktab” nominatsiyasi g‘olibi bo‘ldi. Ularga sertifikat va esdalik so'vg'alari taqdim etildi. Maktab jamoasiga rahmat degan holda ishlariga rivoj tilab qolamiz`,
    link: '#',
  },
  {
    id: 3,
    img: cardImg,
    name: `233-maktab ma'muriyati`,
    date: '11:00, 15-oktabr',
    comment: 22,
    title: `YANGI O‘ZBEKISTON - MAKTAB OSTONASIDAN BOSHLANADI`,
    descr: `🔰Ota-onalarga ta’lim jarayoniga yangicha yondashuv va innovatsion texnologiyalarni joriy etish bo‘yicha yangi loyihalar haqida ma’lumot berildi. Maktab bitiruvchilarining ikkita til va bitta kasbni mukammal egallashi, yoshlarimizning yetuk kadrlar bo'lib yetishishida oliy ta'lim muassasalarining o'rni muhim ekanligiga ham alohida e'tibor qaratildi.`,
    link: '#',
  },
  {
    id: 4,
    img: cardImg,
    name: `111-maktab ma'muriyati`,
    date: '09:30, 6-oktabr',
    comment: 19,
    title: `YANGI O‘ZBEKISTON - MAKTAB OSTONASIDAN BOSHLANADI`,
    descr: `Maktab bitiruvchilarining ikkita til va bitta kasbni mukammal egallashi, yoshlarimizning yetuk kadrlar bo'lib yetishishida oliy ta'lim muassasalarining o'rni muhim ekanligiga ham alohida e'tibor qaratildi. Shuningdek, o'quvchilarning iqtidorini aniqlash va rivojlantirish, ularning o‘zini namoyon etishi uchun shart-sharoit yaratish  muhokama qilindi.`,
    link: '#',
  },
  {
    id: 5,
    img: cardImg,
    name: `111-maktab ma'muriyati`,
    date: '09:30, 6-oktabr',
    comment: 19,
    title: `Kitob ziyo shu'lasi`,
    descr: `📚Olmazor tumanidagi 111-umumta'lim maktabida o'quvchilar va ota-onalar uchun  "Kitob ziyo shu'lasi" shiori ostida kitob marafoni bo'lib o'tdi. Ushbu marafonda ota-onalar  faol ishtirok  etishdi hamda farzandlariga, shu bilan  birga maktab kutubxonasiga kitoblar sovg'a qilishdi!`,
    link: '#',
  },
  {
    id: 6,
    img: cardImg,
    name: `326-maktab ma'muriyati`,
    date: '08:30, 30-sentabr',
    comment: 10,
    title: `Qizil yarim oy jamiati`,
    descr: `Olmazor tumanidagi 326-umumta'lim maktabida 1-oktabr "Ustoz va murabbiylar kuni" munosabati bilan O'zbekiston Qizil Yarim Oy jamiyati Olmazor tuman tashkiloti, tuman Maktabgacha va maktab ta'limi  bo'limi hamkorlikda tadbir tashkil etildi. Tadbirda  Olmazor tumanidagi Maktabgacha va maktab ta'limi muassasalarida faoliyat olib borayotgan 80 nafar jonkuyar ustoz va murabbiylar Qizil Yarim Oy jamiyati Olmazor tuman tashkiloti tomonidan esdalik sovg'alari bilan rag'batlantirildi.`,
    link: '#',
  },
  {
    id: 7,
    img: cardImg,
    name: `106-maktab ma'muriyati`,
    date: '10:30, 8-senatbr',
    comment: 14,
    title: `Jaholatga qarshi ma’rifat`,
    descr: `✔️Tadbirda Din ishlari bo'yicha qo'mita raisi maslahatchisi I.Marupov o'z ma'ruzalari bilan ishtirok etdi.

    ▪️Unda bugungi kunda jaholatga qarshi ma’rifat bilan kurashish har qachongidan ko‘ra muhim ahamiyat kasb etayotgani, vatan qadri, yurt tinchligi, hamjihatlikning qadriga yetish bunda yoshlarni milliy qadriyatlarga sodiq qilib tarbiyalash lozimligi va farzand tarbiyasida ota-onaning o‘rni borasida fikrlar ilgari surildi.`,
    link: '#',
  },
  {
    id: 8,
    img: cardImg,
    name: `133-maktab ma'muriyati`,
    date: '12:00, 25-avgust',
    comment: 10,
    title: `Chet elliklar bilan davra suhbati`,
    descr: `Olmazor tumanidagi 133-sonli ixtisoslashtirilgan davlat umumta'lim maktabiga kun chiqar yurt Yaponiyaning Nagoya shahridan 22 nafar maktab o‘quvchilari 3 nafar yapon murabbiyi boshchiligida tashrif buyurishdi.

    O‘quvchilar tashrif davomida maktab hayoti, O‘zbekistonlik o‘quvchilarning ta'lim olishlari uchun yaratilgan shart-sharoitlar bilan tanishishdi va o‘zbek o‘quvchilari bilan fikr va tajriba almashish maqsadida o‘zaro davra suhbati tashkil qilindi.`,
    link: '#',
  },
  {
    id: 9,
    img: cardImg,
    name: `191-maktab ma'muriyati`,
    date: '10:30, 2-mart',
    comment: 12,
    title: `Biz kelajak uchun javobgarmiz`,
    descr: `Kuni kecha poytaxtimizning 191-sonli maktabida O‘zbekiston ekologik partiyasining Olmazor tuman partiya tashkiloti raisi Shaxnoza Umarxodjayeva tashabbusi bilan maktab o‘quvchilari ishtirokida "Biz kelajak uchun javobgarmiz "mavzusida eko-marafon o‘tkazildi🌍

    Unda O‘zbekiston ekologik partiyasi deputatlari, Toshkent shahar va tuman partiya tashkiloti raislari, eko-aktivistlar hamda Olmazor tumanining 191-sonli maktab o‘qituvchilari va o‘quvchilari ishtirok etdi⚡️`,
    link: '#',
  },
  {
    id: 10,
    img: cardImg,
    name: `249-maktab ma'muriyati`,
    date: '08:30, 28-sentabr',
    comment: 21,
    title: `Xon atlas kuni`,
    descr: `249-maktabda Xon atlsa kuni bo'lib o'tdi va ushbu kunda barcha o'quvchilar o'zimizning milliy kiyimlarimizni kiyib, milliyligimizga hos bo'lgan hatti xarakatlar qilib, o'zbek milliy liboslari qanchalik jozibador ekanligini isbotlab berishdi`,
    link: '#',
  },
];
